"""Build docs/static/data/spell-charts.json (the public Spells page) from spell-survey exports.

usage: python3 tools/export_spell_charts_data.py spell-survey-2026-09-28.json [more exports...]

Later files override earlier ones, as in tools/ingest_spell_survey.py (strategy-article branch),
whose ranking and ++/-- overrides this mirrors: a Bradley-Terry fit over the "which is better?"
answers, cut into the article's tier sizes. Only the charted fields are published; the raw
survey (answer timestamps, per-spell quality votes) stays out of the site.
"""
import json, math, os, sys
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'docs', 'static', 'data', 'spell-charts.json')

# Tier sizes: the article's grouping of the Bradley-Terry order; the last tier takes the rest.
TIERS = [('S', 'Top', 4), ('A', 'Strong', 10), ('B', 'Solid', 5), ('C', 'Middling', 5), ('D', 'Weak', 9), ('F', 'Bottom', None)]

# Extreme ratings given in chat; the survey's 3-level scale maps to +/-, these keep ++/--.
STRONG_SYN = {('Grow', 'Harvest'): 2, ('Flourish', 'Gather'): 2, ('Blossom', 'Erupt'): 2, ('Scatter', 'Erupt'): 2,
              ('Seal_of_Lightning', 'Surge'): 2, ('Seal_of_Lightning', 'Splash'): -2, ('Gust', 'Decay'): 2,
              ('Seal_of_Wind', 'Fireblast'): 2, ('Seal_of_Wind', 'Corrupt'): 2, ('Gust', 'Seal_of_Destruction'): 2}
STRONG_ADV = {('Hail_Storm', 'Blossom'), ('Decay', 'Blossom'), ('Decay', 'Scatter'), ('Gust', 'Seal_of_Destruction')}
STRONG_ADV |= {(c, 'Hurricane') for c in ['Sprout', 'Slash', 'Surge', 'Splash', 'Charge', 'Azimuth', 'Lurk']}


def bradley_terry(names, pairs, eps=0.1):
    W = defaultdict(lambda: defaultdict(float)); games = defaultdict(int); comps = 0
    for k, v in pairs.items():
        a, b = k.split('|'); who = v.get('better')
        if not who: continue
        if who == 'equal': W[a][b] += .5; W[b][a] += .5
        elif who == a: W[a][b] += 1
        elif who == b: W[b][a] += 1
        else: continue
        games[a] += 1; games[b] += 1; comps += 1
    ranked = [n for n in names if games[n]]
    for i in ranked:
        for j in ranked:
            if i != j: W[i][j] += eps / 2
    theta = {n: 0.0 for n in ranked}
    for _ in range(2000):
        new = {}
        for i in ranked:
            wi = sum(W[i][j] for j in ranked if j != i)
            den = sum((W[i][j] + W[j][i]) / (math.exp(theta[i]) + math.exp(theta[j])) for j in ranked if j != i)
            new[i] = math.log(wi / den)
        shift = sum(new.values()) / len(new)
        new = {k: v - shift for k, v in new.items()}
        done = max(abs(new[k] - theta[k]) for k in ranked) < 1e-9
        theta = new
        if done: break
    return theta, games, comps


def main(paths):
    spells, pairs, exported = {}, {}, ''
    for path in paths:
        j = json.load(open(path))
        exported = max(exported, j.get('exportedAt', ''))
        for k, v in j.get('spells', {}).items(): spells.setdefault(k, {}).update(v)
        for k, v in j.get('pairs', {}).items(): pairs.setdefault(k, {}).update(v)
    names = sorted(spells)
    theta, games, comps = bradley_terry(names, pairs)
    order = sorted(theta, key=lambda n: -theta[n])
    tiers, pos = [], 0
    for key, label, size in TIERS:
        take = order[pos:] if size is None else order[pos:pos + size]
        tiers.append({'key': key, 'name': label, 'spells': take}); pos += len(take)
    unranked = [n for n in names if n not in theta]
    if unranked: tiers.append({'key': '?', 'name': 'Not compared', 'spells': unranked})
    matchups, synergies = [], []
    for k, v in sorted(pairs.items()):
        a, b = k.split('|')
        adv = v.get('advantage')
        if adv == 'even': matchups.append([a, b, 0])
        elif adv in (a, b):
            loser = b if adv == a else a
            matchups.append([adv, loser, 2 if (adv, loser) in STRONG_ADV else 1])
        syn = v.get('synergy')
        if syn in ('positive', 'none', 'negative'):
            level = STRONG_SYN.get((a, b), STRONG_SYN.get((b, a)))
            synergies.append([a, b, level if level is not None else {'positive': 1, 'none': 0, 'negative': -1}[syn]])
    out = {
        'about': 'Generated by tools/export_spell_charts_data.py from the spell survey; do not hand-edit.',
        'surveyExportedAt': exported,
        'comparisons': comps,
        'spells': {n: {'type': spells[n].get('type'), 'pack': spells[n].get('pack'), 'board': spells[n].get('board'),
                       'rank': order.index(n) + 1 if n in theta else None} for n in names},
        'tiers': tiers,
        'matchups': matchups,     # [favoured, other, 2 strong | 1 favoured]  or  [a, b, 0] even
        'synergies': synergies,   # [a, b, level]  level in -2..2
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump(out, f, indent=1); f.write('\n')
    print(f'{len(names)} spells, {comps} comparisons, {len(matchups)} matchups, {len(synergies)} synergies -> {os.path.relpath(OUT, REPO)}')


if __name__ == '__main__':
    if len(sys.argv) < 2: sys.exit(__doc__)
    main(sys.argv[1:])
