#!/usr/bin/env python3
"""Generate engine/src/opening_data.rs from the strategy survey.

    python tools/gen_opening_table.py                 # engine/data/opening_survey.json -> engine/src/opening_data.rs
    python tools/gen_opening_table.py --check         # exit 1 if the committed .rs is stale
    python tools/gen_opening_table.py --from-draft docs/strategy/spell_dynamics_draft.md   # refresh the JSON first

The survey block lives on branch `strategy-article` in
docs/strategy/spell_dynamics_draft.md between `<!-- SURVEY-BEGIN` and
`<!-- SURVEY-END -->` (written by tools/ingest_spell_survey.py). Its four tables
-- single-spell ratings, synergy pairs, matchups, Bradley-Terry ranking -- are
kept verbatim in engine/data/opening_survey.json and compiled here into const
tables indexed by ENGINE spell id (engine/src/spells_meta.rs), the way
topology.rs and spells_meta.rs are generated. The opening selector
(engine/src/opening.rs) reads nothing else.

Encoding: MATCHUP[a][b] = +2 / +1 when the survey favours a over b ('++' / '+'),
the mirror entry negative, 0 for '=' or unrated. SYNERGY is symmetric, '++' 2,
'+' 1, '-' -1, '--' -2. BOARD_PREF +1 empty / 0 neither / -1 crowded.
"""
import argparse
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(REPO, 'engine', 'data', 'opening_survey.json')
RS_PATH = os.path.join(REPO, 'engine', 'src', 'opening_data.rs')
META = os.path.join(REPO, 'engine', 'src', 'spells_meta.rs')

PIP = {'++': 2, '+': 1, '=': 0, '-': -1, '--': -2}
PREF = {'empty': 1, 'neither': 0, 'crowded': -1}


def engine_spells():
    """[(id, name)] from spells_meta.rs, in id order."""
    src = open(META, encoding='utf-8').read()
    names = re.findall(r'SpellInfo \{ name: "([A-Za-z_]+)"', src)
    assert len(names) == 39, len(names)
    return names


def parse_draft(path):
    t = open(path, encoding='utf-8').read()
    blk = t.split('<!-- SURVEY-BEGIN')[1].split('<!-- SURVEY-END -->')[0]

    def table(after):
        sec = blk.split(after, 1)[1]
        rows = []
        for line in sec.split('\n'):
            if line.startswith('| ') and not line.startswith('|---'):
                rows.append([c.strip() for c in line.strip('|').split('|')])
            elif line.startswith('#') and rows:
                break
        return rows
    return {'ratings': table('### Single-spell ratings'), 'synergy': table('### Synergy (same player holds both)'),
            'matchups': table('### Matchups (opposite players'), 'bt': table('### Ranking from "which spell is better"')}


def build(data, names):
    idx = {n: i for i, n in enumerate(names)}

    def sid(label):
        key = label.strip().replace(' ', '_')
        if key not in idx:
            raise SystemExit(f'survey spell {label!r} is not an engine spell')
        return idx[key]
    n = len(names)
    strength = [None] * n; pref = [0] * n; quality = [''] * n
    for row in data['bt'][1:]:
        strength[sid(row[1])] = float(row[2])
    for row in data['ratings'][1:]:
        pref[sid(row[0])] = PREF[row[4]]
        quality[sid(row[0])] = row[3]
    missing = [names[i] for i in range(n) if strength[i] is None]
    if missing:
        raise SystemExit(f'no Bradley-Terry strength for {missing}')
    matchup = [[0] * n for _ in range(n)]
    for row in data['matchups'][1:]:
        a, b, r = sid(row[0]), sid(row[1]), PIP[row[2]]
        if matchup[a][b] not in (0, r) or matchup[b][a] not in (0, -r):
            raise SystemExit(f'contradictory matchup {row}')
        matchup[a][b] = r; matchup[b][a] = -r
    synergy = [[0] * n for _ in range(n)]
    for row in data['synergy'][1:]:
        a_l, b_l = [x.strip() for x in row[0].split('+', 1)]
        a, b, r = sid(a_l), sid(b_l), PIP[row[1]]
        if synergy[a][b] not in (0, r):
            raise SystemExit(f'contradictory synergy {row}')
        synergy[a][b] = r; synergy[b][a] = r
    return strength, pref, quality, matchup, synergy


def render(strength, pref, quality, matchup, synergy, names, export):
    def row(v):
        return '[' + ', '.join(f'{x:>2}' for x in v) + ']'
    out = [
        '// GENERATED by tools/gen_opening_table.py from engine/data/opening_survey.json',
        f'// (strategy survey export {export}); do not edit by hand -- rerun the tool.',
        '//',
        '// Spell-strength, board-preference, matchup and synergy tables for the',
        '// competitive opening selector (opening.rs), indexed by ENGINE spell id',
        '// (spells_meta.rs). Units: STRENGTH is the survey\'s Bradley-Terry log-odds;',
        '// MATCHUP[a][b] = +2/+1 when a is favoured against b (mirror negative);',
        '// SYNERGY symmetric, ++ 2 / + 1 / - -1 / -- -2; BOARD_PREF +1 empty, -1 crowded.',
        '',
        f'pub const SURVEY_EXPORT: &str = "{export}";',
        '',
        '/// Bradley-Terry strength by spell id.',
        'pub const STRENGTH: [f32; 39] = [',
    ]
    for i, nm in enumerate(names):
        out.append(f'    {strength[i]:.2f}, // {i:2} {nm} ({quality[i]})')
    out += ['];', '', '/// +1 better on an empty board, 0 no preference, -1 better crowded.',
            'pub const BOARD_PREF: [i8; 39] = ' + row(pref) + ';', '',
            '/// [a][b] > 0: a is favoured against b.', 'pub const MATCHUP: [[i8; 39]; 39] = [']
    for i, nm in enumerate(names):
        out.append(f'    {row(matchup[i])}, // {nm}')
    out += ['];', '', '/// Symmetric synergy when one player holds both.', 'pub const SYNERGY: [[i8; 39]; 39] = [']
    for i, nm in enumerate(names):
        out.append(f'    {row(synergy[i])}, // {nm}')
    out += ['];', '',
            '/// Movement charms whose held stone evicts a contesting stone from a shared sigil.',
            'pub const PUSH_CHARMS: [u8; 2] = [11, 23]; // Slash, Charge', '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--from-draft', default='')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--export', default='2026-09-07')
    a = ap.parse_args()
    if a.from_draft:
        data = parse_draft(a.from_draft)
        json.dump(data, open(JSON_PATH, 'w', encoding='utf-8'), indent=0)
        print(f'wrote {JSON_PATH}')
    data = json.load(open(JSON_PATH, encoding='utf-8'))
    names = engine_spells()
    text = render(*build(data, names), names, a.export)
    if a.check:
        cur = open(RS_PATH, encoding='utf-8').read() if os.path.exists(RS_PATH) else ''
        if cur != text:
            print('engine/src/opening_data.rs is stale; rerun tools/gen_opening_table.py'); sys.exit(1)
        print('opening_data.rs is current'); return
    open(RS_PATH, 'w', encoding='utf-8').write(text)
    print(f'wrote {RS_PATH}')


if __name__ == '__main__':
    main()
