"""Regenerate the survey-derived sections of spell_dynamics_draft.md from one or
more spell-survey-*.json exports (later files override earlier ones).

usage: python3 tools/ingest_spell_survey.py spell-survey-2026-09-06.json [more.json ...]
"""
import json, sys, re, os
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAFT = os.path.join(REPO, 'spell_dynamics_draft.md')
STATS = os.path.join(REPO, 'tools', 'spell_stats2.json')  # optional copy of the data tier fit

# Pairs Robi rated at the extreme in chat; the 3-level survey maps to +/-, these keep ++/--.
STRONG_SYN = {('Grow','Harvest'):'++', ('Flourish','Gather'):'++', ('Blossom','Erupt'):'++', ('Scatter','Erupt'):'++',
              ('Seal_of_Lightning','Surge'):'++', ('Seal_of_Lightning','Splash'):'--', ('Gust','Decay'):'++'}
STRONG_ADV = {('Hail_Storm','Blossom'):'++', ('Decay','Blossom'):'++', ('Decay','Scatter'):'++'}
for c in ['Sprout','Slash','Surge','Splash','Charge','Azimuth','Lurk']: STRONG_ADV[(c,'Hurricane')] = '++'  # charm beats Hurricane

pretty = lambda n: n.replace('_', ' ')
spells, pairs = {}, {}
for path in sys.argv[1:]:
    j = json.load(open(path))
    for k, v in j.get('spells', {}).items(): spells.setdefault(k, {}).update(v)
    for k, v in j.get('pairs', {}).items(): pairs.setdefault(k, {}).update(v)

ORDER_Q = {'good': 0, 'medium': 1, 'bad': 2}
lines = ['<!-- SURVEY-BEGIN (generated by tools/ingest_spell_survey.py; do not hand-edit) -->',
         f'## Survey results (Robi, latest export {max(json.load(open(p))["exportedAt"] for p in sys.argv[1:])[:10]})', '']
# --- single spells ---
lines += ['### Single-spell ratings', '', '| Spell | Pack | Type | Quality | Better on | Source |', '|---|---|---|---|---|---|']
for k, v in sorted(spells.items(), key=lambda kv: (ORDER_Q.get(kv[1].get('quality'), 9), kv[0])):
    lines.append(f"| {pretty(k)} | {v.get('pack','')} | {v.get('type','')} | {v.get('quality','?')} | {v.get('board','?')} | {v.get('source','')} |")
by_board = defaultdict(list)
for k, v in spells.items(): by_board[v.get('board')].append(pretty(k))
lines += ['', '**Board preference summary**', '']
for b in ('empty', 'neither', 'crowded'):
    lines.append(f"- {b}: {', '.join(sorted(by_board.get(b, [])))}")
# --- synergy ---
def syn_symbol(a, b, s):
    key = (a, b) if (a, b) in STRONG_SYN else (b, a)
    if key in STRONG_SYN: return STRONG_SYN[key]
    return {'positive': '+', 'none': '=', 'negative': '-'}.get(s, '?')
def adv_symbol(a, b, adv):
    if adv == 'even': return '=', None
    if adv not in (a, b): return '?', None
    other = b if adv == a else a
    return (STRONG_ADV.get((adv, other), '+')), adv
lines += ['', '### Synergy (same player holds both)', '', '| Pair | Rating | Source |', '|---|---|---|']
syn_rows = []
for k, v in pairs.items():
    if 'synergy' not in v: continue
    a, b = k.split('|'); sym = syn_symbol(a, b, v['synergy'])
    syn_rows.append((sym, f"| {pretty(a)} + {pretty(b)} | {sym} | {v.get('source','')} |"))
rank = {'++': 0, '+': 1, '-': 3, '--': 4, '=': 2}
for _, r in sorted(syn_rows, key=lambda x: (rank.get(x[0], 9), x[1])): lines.append(r)
# --- matchups ---
lines += ['', '### Matchups (opposite players; rating is for the favoured spell)', '', '| Favoured | vs | Rating | Source |', '|---|---|---|---|']
adv_rows = []
for k, v in pairs.items():
    if 'advantage' not in v: continue
    a, b = k.split('|'); sym, who = adv_symbol(a, b, v['advantage'])
    if who is None: adv_rows.append((2, f"| {pretty(a)} | {pretty(b)} | = | {v.get('source','')} |"))
    else:
        other = b if who == a else a
        adv_rows.append((rank[sym], f"| {pretty(who)} | {pretty(other)} | {sym} | {v.get('source','')} |"))
for _, r in sorted(adv_rows): lines.append(r)
# --- data vs Robi ---
if os.path.exists(STATS):
    st = json.load(open(STATS)); STATIC = {k for k in spells if spells[k].get('type') == 'charm' and False}
    lines += ['', '### Data tier fit vs Robi quality (log-odds per cast; seals: held ≥1 turn)', '', '| Spell | Robi | data c | flag |', '|---|---|---|---|']
    for k, v in sorted(spells.items(), key=lambda kv: -(st['coef_count'].get(kv[0], [0])[0])):
        c = st['coef_ind'][k][0] if k.startswith('Seal_') else st['coef_count'][k][0]
        q = v.get('quality'); flag = ''
        if q == 'bad' and c > 0.6: flag = 'data likes it more'
        if q == 'good' and c < 0.3: flag = 'data likes it less'
        lines.append(f"| {pretty(k)} | {q} | {c:+.2f} | {flag} |")
# --- ranking from "which spell is better" (Bradley-Terry, ties = half a win each) ---
import math
comps = [(k.split('|'), v['better']) for k, v in pairs.items() if v.get('better')]
names = sorted({n for (a, b), _ in comps for n in (a, b)} | set(spells))
if comps:
    wins = defaultdict(float); games = defaultdict(float)
    W = defaultdict(lambda: defaultdict(float))  # W[i][j] = wins of i over j
    for (a, b), who in comps:
        if who == 'equal': W[a][b] += .5; W[b][a] += .5
        elif who == a: W[a][b] += 1
        elif who == b: W[b][a] += 1
        else: continue
        games[a] += 1; games[b] += 1
    ranked = [n for n in names if games[n] > 0]
    # Regularize: every pair also gets a virtual tie of weight EPS so a spell
    # with one win is not infinitely strong. Standard MM (Hunter 2004) update.
    EPS = 0.1
    for i in ranked:
        for j in ranked:
            if i != j: W[i][j] += EPS / 2
    theta = {n: 0.0 for n in ranked}
    for _ in range(2000):
        new = {}
        for i in ranked:
            wi = sum(W[i][j] for j in ranked if j != i)
            denom = sum((W[i][j] + W[j][i]) / (math.exp(theta[i]) + math.exp(theta[j])) for j in ranked if j != i)
            new[i] = math.log(wi / denom)
        shift = sum(new.values()) / len(new)
        new = {k: v - shift for k, v in new.items()}
        done = max(abs(new[k] - theta[k]) for k in ranked) < 1e-9
        theta = new
        if done: break
    lines += ['', f'### Ranking from "which spell is better" ({len(comps)} comparisons, Bradley-Terry)', '',
              '| # | Spell | Strength | Comparisons | Robi quality |', '|---|---|---|---|---|']
    for r, n in enumerate(sorted(ranked, key=lambda n: -theta[n]), 1):
        lines.append(f"| {r} | {pretty(n)} | {theta[n]:+.2f} | {int(games[n])} | {spells.get(n, {}).get('quality', '')} |")
    unranked = [pretty(n) for n in names if games[n] == 0]
    if unranked: lines += ['', 'Not yet compared: ' + ', '.join(unranked)]
else:
    lines += ['', '### Ranking from "which spell is better"', '', 'No comparisons yet (the third pair question was added 2026-09-06).']
lines += ['<!-- SURVEY-END -->']
block = '\n'.join(lines) + '\n'
s = open(DRAFT).read()
if '<!-- SURVEY-BEGIN' in s:
    s = re.sub(r'<!-- SURVEY-BEGIN.*?<!-- SURVEY-END -->\n', lambda m: block, s, flags=re.S)
else:
    s = s.replace('## 1. Board crowdedness', block + '\n## 1. Board crowdedness (MY PRE-SURVEY GUESSES — superseded where the survey has an answer)', 1)
open(DRAFT, 'w').write(s)
print(f"ingested {len(spells)} spells, {len(pairs)} pairs -> {DRAFT}")
