//! GENERATED by engine/harness/fit_opening_selector.py --rust; do not edit.
//! Placeholder (all zero) until the rollout fit lands.
pub const LEARNED_RED: [i32; 79] = [0; 79];
pub const LEARNED_BLUE: [i32; 79] = [0; 79];
